Prevent error if value is None
  File "/config/custom_components/luxtronik2/common.py", line 81, in correct_key_value
    value = value.replace(" ", "_").replace("/", "_").lower()
            ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'replace'